### ISSUE TITLE
SIGSEGV : invalid memory address or nil pointer (dns)

### ISSUE THREAD

**Issue by baylanger** [erkexzcx/stoppropaganda#109]
!!! Lots of great changes since past 24h 🚀 !!!

With 1500 dns workers, the process crashed after ~15 minutes.  Stack trace shows it does happen in the dns library.  Running with 4k workers, the process crashes within ~3-4 minutes... but at 1k I saw, it also crashed once within few seconds.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104996e44]

goroutine 5493 [running]:
strings.IndexByte(...)
	/opt/homebrew/Cellar/go/1.17.8/libexec/src/strings/strings.go:114
strings.Index({0x0, 0x14}, {0x104c342e9, 0x1})
	/opt/homebrew/Cellar/go/1.17.8/libexec/src/strings/strings.go:1030 +0x160
strings.Contains(...)
	/opt/homebrew/Cellar/go/1.17.8/libexec/src/strings/strings.go:62
github.com/miekg/dns.domainNameLen({0x0, 0x14}, 0xc, 0x0, 0x1)
	/Users/belanger/git/stoppropaganda/vendor/github.com/miekg/dns/msg.go:994 +0x78
github.com/miekg/dns.(*Question).len(...)
	/Users/belanger/git/stoppropaganda/vendor/github.com/miekg/dns/types.go:235
github.com/miekg/dns.msgLenWithCompressionMap(0x140000b06c0, 0x0)
	/Users/belanger/git/stoppropaganda/vendor/github.com/miekg/dns/msg.go:968 +0xb0
github.com/miekg/dns.(*Msg).packBufferWithCompressionMap(0x140000b06c0, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0)
	/Users/belanger/git/stoppropaganda/vendor/github.com/miekg/dns/msg.go:789 +0x160
github.com/miekg/dns.(*Msg).PackBuffer(0x140000b06c0, {0x0, 0x0, 0x0})
	/Users/belanger/git/stoppropaganda/vendor/github.com/miekg/dns/msg.go:735 +0xf0
github.com/miekg/dns.(*Msg).Pack(...)
	/Users/belanger/git/stoppropaganda/vendor/github.com/miekg/dns/msg.go:723
github.com/miekg/dns.(*Conn).WriteMsg(0x14006130dc0, 0x140000b06c0)
	/Users/belanger/git/stoppropaganda/vendor/github.com/miekg/dns/client.go:363 +0xe0
github.com/miekg/dns.(*Client).exchangeContext(0x1400015c380, {0x104d2b930, 0x1400001c0b0}, 0x140000b06c0, 0x14006130dc0)
	/Users/belanger/git/stoppropaganda/vendor/github.com/miekg/dns/client.go:240 +0x334
github.com/miekg/dns.(*Client).exchangeWithConnContext(0x1400015c380, {0x104d2b930, 0x1400001c0b0}, 0x140000b06c0, 0x14006130dc0)
	/Users/belanger/git/stoppropaganda/vendor/github.com/miekg/dns/client.go:195 +0x1dc
github.com/miekg/dns.(*Client).ExchangeWithConn(0x1400015c380, 0x140000b06c0, 0x14006130dc0)
	/Users/belanger/git/stoppropaganda/vendor/github.com/miekg/dns/client.go:190 +0x54
github.com/miekg/dns.(*Client).Exchange(0x1400015c380, 0x140000b06c0, {0x104c37a1c, 0x10})
	/Users/belanger/git/stoppropaganda/vendor/github.com/miekg/dns/client.go:170 +0xd4
github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.runDNSWorker(0x14000fd7620)
	/Users/belanger/git/stoppropaganda/internal/stoppropaganda/dns.go:66 +0xc0
created by github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.startDNS
```

Will try to lower at 500 and see how it goes but it does look like it's a 🐛

**Comment by baylanger** [comment]
```
-dnsworkers int
    	DOS each DNS server with this amount of workers (100)
```

Maybe 1000 / server is too much 🤔 , for sure 4k is a lot 💣

**Comment by baylanger** [comment]
I'm still getting a segmentation fault with...

. workers 1k
. dnsworkers 500

**Comment by deputinizer** [comment]
string == nil ?
Weird.
https://github.com/miekg/dns/blob/master/msg.go#L994
https://github.com/miekg/dns/blob/master/types.go#L235

**Comment by deputinizer** [comment]
Ok, it's a race condition :/ we shouldn't modify domain name from multiple threads
https://github.com/erkexzcx/stoppropaganda/blob/main/internal/stoppropaganda/dns.go#L65

**Comment by deputinizer** [comment]
Fixed in https://github.com/erkexzcx/stoppropaganda/pull/108

**Comment by erkexzcx** [comment]
@deputinizer nice dedication :)
