### ISSUE TITLE
Raspberry pi crash

### ISSUE THREAD

**Issue by 0xzheo** [erkexzcx/stoppropaganda#63]
In recent versions, 3 minutes after running just the go binary, the program seems to crash:

```
...
goroutine 2804 [select]:
net/http.(*Transport).getConn(0x1130340, 0x9052160, {{}, 0x0, {0x2eb719, 0x5}, {0x99dfc50, 0xd}, 0x0})
        /usr/local/go/src/net/http/transport.go:1372 +0x494
net/http.(*Transport).roundTrip(0x1130340, 0x4dcab00)
        /usr/local/go/src/net/http/transport.go:581 +0x78c
net/http.(*Transport).RoundTrip(0x1130340, 0x4dcab00)
        /usr/local/go/src/net/http/roundtrip.go:18 +0x24
net/http.send(0x1869280, {0x34ea6c, 0x1130340}, {0xc07ffc0b50630ff1, 0x467346618e, 0x4d6248})
        /usr/local/go/src/net/http/client.go:252 +0x540
net/http.(*Client).send(0x4d6188, 0x1869280, {0xc07ffc0b50630ff1, 0x467346618e, 0x4d6248})
        /usr/local/go/src/net/http/client.go:176 +0x94
net/http.(*Client).do(0x4d6188, 0x1869280)
        /usr/local/go/src/net/http/client.go:725 +0x93c
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:593
github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start.func1()
        /home/pi/stoppropaganda/internal/stoppropaganda/websites.go:368 +0x444
created by github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start
        /home/pi/stoppropaganda/internal/stoppropaganda/websites.go:423 +0x49c

goroutine 2805 [select]:
net/http.(*Transport).getConn(0x1130340, 0xbab4c60, {{}, 0x0, {0x2eb719, 0x5}, {0xbb4a490, 0xd}, 0x0})
        /usr/local/go/src/net/http/transport.go:1372 +0x494
net/http.(*Transport).roundTrip(0x1130340, 0x9e3a680)
        /usr/local/go/src/net/http/transport.go:581 +0x78c
net/http.(*Transport).RoundTrip(0x1130340, 0x9e3a680)
        /usr/local/go/src/net/http/roundtrip.go:18 +0x24
net/http.send(0x1869280, {0x34ea6c, 0x1130340}, {0xc07ffc0b20fa7e90, 0x4648430609, 0x4d6248})
        /usr/local/go/src/net/http/client.go:252 +0x540
net/http.(*Client).send(0x4d6188, 0x1869280, {0xc07ffc0b20fa7e90, 0x4648430609, 0x4d6248})
        /usr/local/go/src/net/http/client.go:176 +0x94
net/http.(*Client).do(0x4d6188, 0x1869280)
        /usr/local/go/src/net/http/client.go:725 +0x93c
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:593
github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start.func1()
        /home/pi/stoppropaganda/internal/stoppropaganda/websites.go:368 +0x444
created by github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start
        /home/pi/stoppropaganda/internal/stoppropaganda/websites.go:423 +0x49c

goroutine 2806 [select]:
net/http.(*Transport).getConn(0x1130340, 0x7658ac0, {{}, 0x0, {0x2eb719, 0x5}, {0x4dfa440, 0xd}, 0x0})
        /usr/local/go/src/net/http/transport.go:1372 +0x494
net/http.(*Transport).roundTrip(0x1130340, 0x4c6fc80)
        /usr/local/go/src/net/http/transport.go:581 +0x78c
net/http.(*Transport).RoundTrip(0x1130340, 0x4c6fc80)
        /usr/local/go/src/net/http/roundtrip.go:18 +0x24
net/http.send(0x1869280, {0x34ea6c, 0x1130340}, {0xc07ffc0b558a8865, 0x46786dd9ef, 0x4d6248})
        /usr/local/go/src/net/http/client.go:252 +0x540
net/http.(*Client).send(0x4d6188, 0x1869280, {0xc07ffc0b558a8865, 0x46786dd9ef, 0x4d6248})
        /usr/local/go/src/net/http/client.go:176 +0x94
net/http.(*Client).do(0x4d6188, 0x1869280)
        /usr/local/go/src/net/http/client.go:725 +0x93c
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:593
github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start.func1()
        /home/pi/stoppropaganda/internal/stoppropaganda/websites.go:368 +0x444
created by github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start
        /home/pi/stoppropaganda/internal/stoppropaganda/websites.go:423 +0x49c

goroutine 2807 [select]:
net/http.(*Transport).getConn(0x1130340, 0x844b6e0, {{}, 0x0, {0x2eb719, 0x5}, {0xa0001e0, 0xd}, 0x0})
        /usr/local/go/src/net/http/transport.go:1372 +0x494
net/http.(*Transport).roundTrip(0x1130340, 0x8094500)
        /usr/local/go/src/net/http/transport.go:581 +0x78c
net/http.(*Transport).RoundTrip(0x1130340, 0x8094500)
        /usr/local/go/src/net/http/roundtrip.go:18 +0x24
net/http.send(0x1869280, {0x34ea6c, 0x1130340}, {0xc07ffc0b1cbd4d79, 0x464405d516, 0x4d6248})
        /usr/local/go/src/net/http/client.go:252 +0x540
net/http.(*Client).send(0x4d6188, 0x1869280, {0xc07ffc0b1cbd4d79, 0x464405d516, 0x4d6248})
        /usr/local/go/src/net/http/client.go:176 +0x94
net/http.(*Client).do(0x4d6188, 0x1869280)
        /usr/local/go/src/net/http/client.go:725 +0x93c
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:593
github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start.func1()
        /home/pi/stoppropaganda/internal/stoppropaganda/websites.go:368 +0x444
created by github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start
        /home/pi/stoppropaganda/internal/stoppropaganda/websites.go:423 +0x49c

goroutine 2808 [select]:
net/http.(*Transport).getConn(0x1130340, 0x8a22d60, {{}, 0x0, {0x2eb719, 0x5}, {0x829cce0, 0xd}, 0x0})
        /usr/local/go/src/net/http/transport.go:1372 +0x494
net/http.(*Transport).roundTrip(0x1130340, 0x5159c00)
        /usr/local/go/src/net/http/transport.go:581 +0x78c
net/http.(*Transport).RoundTrip(0x1130340, 0x5159c00)
        /usr/local/go/src/net/http/roundtrip.go:18 +0x24
net/http.send(0x1869280, {0x34ea6c, 0x1130340}, {0xc07ffc0b2e3982ca, 0x4655820a55, 0x4d6248})
        /usr/local/go/src/net/http/client.go:252 +0x540
net/http.(*Client).send(0x4d6188, 0x1869280, {0xc07ffc0b2e3982ca, 0x4655820a55, 0x4d6248})
        /usr/local/go/src/net/http/client.go:176 +0x94
net/http.(*Client).do(0x4d6188, 0x1869280)
        /usr/local/go/src/net/http/client.go:725 +0x93c
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:593
github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start.func1()
        /home/pi/stoppropaganda/internal/stoppropaganda/websites.go:368 +0x444
created by github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start
        /home/pi/stoppropaganda/internal/stoppropaganda/websites.go:423 +0x49c

goroutine 2809 [select]:
net/http.(*Transport).getConn(0x1130340, 0xaaa6e20, {{}, 0x0, {0x2eb719, 0x5}, {0x431d340, 0xd}, 0x0})
        /usr/local/go/src/net/http/transport.go:1372 +0x494
net/http.(*Transport).roundTrip(0x1130340, 0xa4e2a00)
        /usr/local/go/src/net/http/transport.go:581 +0x78c
net/http.(*Transport).RoundTrip(0x1130340, 0xa4e2a00)
        /usr/local/go/src/net/http/roundtrip.go:18 +0x24
net/http.send(0x1869280, {0x34ea6c, 0x1130340}, {0xc07ffc0b970cace2, 0x46b58ac86d, 0x4d6248})
        /usr/local/go/src/net/http/client.go:252 +0x540
net/http.(*Client).send(0x4d6188, 0x1869280, {0xc07ffc0b970cace2, 0x46b58ac86d, 0x4d6248})
        /usr/local/go/src/net/http/client.go:176 +0x94
net/http.(*Client).do(0x4d6188, 0x1869280)
        /usr/local/go/src/net/http/client.go:725 +0x93c
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:593
github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start.func1()
        /home/pi/stoppropaganda/internal/stoppropaganda/websites.go:368 +0x444
created by github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start
        home/pi/stoppropaganda/internal/stoppropaganda/websites.go:423 +0x49c
...
```

Go version:
```
pi@raspberrypi:~/stoppropaganda $ go version
go version go1.17.7 linux/arm
```

**Comment by erkexzcx** [comment]
How did you run (the full command)? Are you sure your RPI did not ran out of RAM and memkiller took action?

Does it happen the same if you just something like `-workers 1 -dnsworkers 1`?

Also have sufficient power supply and there are no hardware faults? (from my experience - yes, RPIs are very fault-intolerant)

**Comment by deputinizer** [comment]
Please run with `2> err.txt`

Like:
`./stoppropaganda -workers 1 -dnsworkers 1 2> err.txt`
