### ISSUE TITLE
Crashing (fasthttp-related errors)

### ISSUE THREAD

**Issue by erkexzcx** [erkexzcx/stoppropaganda#67]
```
goroutine 6332838 [select]:
net.(*netFD).connect.func2()
        /usr/lib/go/src/net/fd_unix.go:119 +0x9e
created by net.(*netFD).connect
        /usr/lib/go/src/net/fd_unix.go:118 +0x385
```

And a bunch of other errors. I am currently looking for a root cause.

**Comment by deputinizer** [comment]
Crashes with:
`./dist/stoppropaganda_v0.0.25_linux_x86_64 -workers 1 -dnsworkers 1 -h 2> err.txt`

Log:
```
$ head -n 45 err.txt
2022/03/02 15:50:23 Started!
fatal error: sync: unlock of unlocked mutex

goroutine 83 [running]:
runtime.throw({0x71aa1c, 0x4e05d09ed05})
        /home/test/go/src/runtime/panic.go:1198 +0x71 fp=0xc00053eed8 sp=0xc00053eea8 pc=0x4326b1
sync.throw({0x71aa1c, 0xc00046e6e0})
        /home/test/go/src/runtime/panic.go:1184 +0x1e fp=0xc00053eef8 sp=0xc00053eed8 pc=0x45ca5e
sync.(*Mutex).unlockSlow(0xc0000158c8, 0xffffffff)
        /home/test/go/src/sync/mutex.go:196 +0x3c fp=0xc00053ef20 sp=0xc00053eef8 pc=0x469c1c
sync.(*Mutex).Unlock(...)
        /home/test/go/src/sync/mutex.go:190
github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start.func1()
        /home/test/stoppropaganda/internal/stoppropaganda/websites.go:366 +0x429 fp=0xc00053efe0 sp=0xc00053ef20 pc=0x69bba9
runtime.goexit()
        /home/test/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00053efe8 sp=0xc00053efe0 pc=0x460ce1
created by github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.(*Website).Start
        /home/test/stoppropaganda/internal/stoppropaganda/websites.go:408 +0x2eb

goroutine 1 [IO wait, 4 minutes]:
internal/poll.runtime_pollWait(0x7f775de57e30, 0x72)
        /home/test/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc00014c680, 0x417f29, 0x0)
        /home/test/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /home/test/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00014c680)
        /home/test/go/src/internal/poll/fd_unix.go:402 +0x22c
net.(*netFD).accept(0xc00014c680)
        /home/test/go/src/net/fd_unix.go:173 +0x35
net.(*TCPListener).accept(0xc00000c2e8)
        /home/test/go/src/net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).AcceptTCP(0xc00000c2e8)
        /home/test/go/src/net/tcpsock.go:249 +0x3d
github.com/valyala/fasthttp.tcpKeepaliveListener.Accept({0xc00000c2e8, 0x60, 0x40c974})
        /home/test/stoppropaganda/vendor/github.com/valyala/fasthttp/server.go:1555 +0x2b
github.com/valyala/fasthttp.acceptConn(0xc00010c6c0, {0x77b8d8, 0xc00000c300}, 0xc000043dc8)
        /home/test/stoppropaganda/vendor/github.com/valyala/fasthttp/server.go:1900 +0x62
github.com/valyala/fasthttp.(*Server).Serve(0xc00010c6c0, {0x77b8d8, 0xc00000c300})
        /home/test/stoppropaganda/vendor/github.com/valyala/fasthttp/server.go:1813 +0x4ea
github.com/valyala/fasthttp.(*Server).ListenAndServe(0xc00010c6c0, {0x7ffdfe6ad7fa, 0x716abb})
        /home/test/stoppropaganda/vendor/github.com/valyala/fasthttp/server.go:1584 +0xae
github.com/valyala/fasthttp.ListenAndServe(...)
        /home/test/stoppropaganda/vendor/github.com/valyala/fasthttp/server.go:92
github.com/erkexzcx/stoppropaganda/internal/stoppropaganda.Start()
```

**Comment by erkexzcx** [comment]
I am currently working on it

**Comment by erkexzcx** [comment]
This seems to be different error - I just noticed the bug with usage of `ws.pauseMux.Unlock()` [in here](https://github.com/erkexzcx/stoppropaganda/blob/main/internal/stoppropaganda/websites.go#L343-L366). :facepalm: My bad. Fixing right now...

**Comment by deputinizer** [comment]
https://github.com/deputinizer/stoppropaganda/commit/e79f0b818aa32c911df9d5ec9dfe4340ec82b934

**Comment by deputinizer** [comment]
Good job https://github.com/erkexzcx/stoppropaganda/pull/71/commits/5aad446d1556c40743177cf508d66d025116dcf5?diff=split&w=0#diff-0908e7d3eab511451d91971f89ba980d2c0b1026535ba4486951adfe9685413aR366

**Comment by erkexzcx** [comment]
https://github.com/erkexzcx/stoppropaganda/releases/tag/v0.0.27
